package Verein;

/**
* Verein/VereinsMitgliedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vmitglied.idl
* Sonntag, 21. Mai 2017 11:54 Uhr MESZ
*/

public final class VereinsMitgliedHolder implements org.omg.CORBA.portable.Streamable
{
  public Verein.VereinsMitglied value = null;

  public VereinsMitgliedHolder ()
  {
  }

  public VereinsMitgliedHolder (Verein.VereinsMitglied initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Verein.VereinsMitgliedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Verein.VereinsMitgliedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Verein.VereinsMitgliedHelper.type ();
  }

}
