package Verein;


/**
* Verein/VereinsMitgliedOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vmitglied.idl
* Sonntag, 21. Mai 2017 11:54 Uhr MESZ
*/

public interface VereinsMitgliedOperations 
{
  String mname ();
  Verein.VereinsMitgliedPackage.verein[] mvereine ();
  short erhoeheBeitrag (String verein, short erhoehung);
} // interface VereinsMitgliedOperations
